#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALS_OverlayState

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ALS_OverlayState.ALS_OverlayState
// NumValues: 0x000E
enum class EALS_OverlayState : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator12                          = 1,
	NewEnumerator13                          = 2,
	NewEnumerator14                          = 3,
	NewEnumerator15                          = 4,
	NewEnumerator1                           = 5,
	NewEnumerator5                           = 6,
	NewEnumerator10                          = 7,
	NewEnumerator6                           = 8,
	NewEnumerator7                           = 9,
	NewEnumerator8                           = 10,
	NewEnumerator9                           = 11,
	NewEnumerator11                          = 12,
	ALS_MAX                                  = 13,
};

}

