#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bones02_BP

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Bones02_BP.Bones02_BP_C
// 0x0010 (0x02A8 - 0x0298)
class ABones02_BP_C final : public AActor
{
public:
	class UStaticMeshComponent*                   SM_bone_leg_01;                                    // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Bones02_BP_C">();
	}
	static class ABones02_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABones02_BP_C>();
	}
};
static_assert(alignof(ABones02_BP_C) == 0x000008, "Wrong alignment on ABones02_BP_C");
static_assert(sizeof(ABones02_BP_C) == 0x0002A8, "Wrong size on ABones02_BP_C");
static_assert(offsetof(ABones02_BP_C, SM_bone_leg_01) == 0x000298, "Member 'ABones02_BP_C::SM_bone_leg_01' has a wrong offset!");
static_assert(offsetof(ABones02_BP_C, DefaultSceneRoot) == 0x0002A0, "Member 'ABones02_BP_C::DefaultSceneRoot' has a wrong offset!");

}

