#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MenuButtons

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_MenuButtons.BP_MenuButtons_C.ExecuteUbergraph_BP_MenuButtons
// 0x1008 (0x1008 - 0x0000)
struct BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_NormalizedDeltaRotator_ReturnValue;       // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_NormalizedDeltaRotator_ReturnValue_1;     // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0038(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0050(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0068(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x0080(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_MakeVector_ReturnValue_2;                 // 0x0098(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_2;                // 0x00B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	double                                        CallFunc_Lerp_ReturnValue;                         // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_3;                 // 0x00D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_ReturnValue_1;                       // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_4;                 // 0x00F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_ReturnValue_2;                       // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0110(0x0010)(ConstParm, ReferenceParm)
	struct FVector                                CallFunc_MakeVector_ReturnValue_5;                 // 0x0120(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x0138(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_RLerp_ReturnValue;                        // 0x0150(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x016A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x016B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_2;                     // 0x016C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_2;               // 0x016D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_3;                     // 0x016E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_4;                     // 0x016F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_3;               // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_4;               // 0x0171(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_5;               // 0x0172(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_173[0x5];                                      // 0x0173(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue;       // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue_1;     // 0x0188(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToActor_ReturnValue;             // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_191[0x7];                                      // 0x0191(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult;    // 0x0198(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0280(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult_1;  // 0x0368(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_1;  // 0x0450(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult_2;  // 0x0538(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_2;  // 0x0620(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_3;  // 0x0708(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_4;  // 0x07F0(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_5;  // 0x08D8(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x09C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C4[0x4];                                      // 0x09C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x09C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x09D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_3;                // 0x09D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_DeprojectMousePositionToWorld_WorldLocation; // 0x09F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_DeprojectMousePositionToWorld_WorldDirection; // 0x0A08(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DeprojectMousePositionToWorld_ReturnValue; // 0x0A20(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A21[0x7];                                      // 0x0A21(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue_2;     // 0x0A28(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x0A30(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0A48(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0A60(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0A78(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0B60(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Highlight_2;                    // 0x0B61(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0B62(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0B63(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0B64(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0B68(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B6C[0x4];                                      // 0x0B6C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0B70(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0B88(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0BA0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0BB8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0BD0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0BD8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0BE0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0BE8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x0BF0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0BF8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x0BFC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0C00(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C04[0x4];                                      // 0x0C04(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0C08(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0C20(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x0C38(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchName_CmpSuccess;                      // 0x0C40(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0C41(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Highlight_1;                    // 0x0C42(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_5;                     // 0x0C43(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Highlight;                      // 0x0C44(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C45[0x3];                                      // 0x0C45(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UUserWidget*>                    CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0C48(0x0010)(ReferenceParm, ContainsInstancedReference)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0C58(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class UUserWidget*>                    CallFunc_RemoveSaveWidget_WidgetsOut;              // 0x0C60(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UUserWidget*                            CallFunc_Array_Get_Item_1;                         // 0x0C70(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0C78(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C7C[0x4];                                      // 0x0C7C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_W_C*                          K2Node_DynamicCast_AsMain_Menu_W;                  // 0x0C80(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0C88(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0C89(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C8A[0x6];                                      // 0x0C8A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0C90(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class APC_MainMenu_C*                         K2Node_DynamicCast_AsPC_Main_Menu;                 // 0x0CA0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0CA8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CA9[0x7];                                      // 0x0CA9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0CB0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_3;        // 0x0CB8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APC_MainMenu_C*                         K2Node_DynamicCast_AsPC_Main_Menu_1;               // 0x0CC0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0CC8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CC9[0x7];                                      // 0x0CC9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APC_MainMenu_C*                         K2Node_DynamicCast_AsPC_Main_Menu_2;               // 0x0CD0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0CD8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CD9[0x7];                                      // 0x0CD9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_AddRelativeRotation_SweepHitResult;    // 0x0CE0(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0DC8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VLerp_ReturnValue;                        // 0x0DE0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_6;  // 0x0DF8(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult_3;  // 0x0EE0(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_MakeVector_Z_ImplicitCast;                // 0x0FC8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MakeVector_Z_ImplicitCast_1;              // 0x0FD0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MakeVector_Z_ImplicitCast_2;              // 0x0FD8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_Alpha_ImplicitCast;                  // 0x0FE0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_Alpha_ImplicitCast_1;                // 0x0FE8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_Alpha_ImplicitCast_2;                // 0x0FF0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0FF8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Yaw_ImplicitCast;             // 0x1000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons) == 0x000008, "Wrong alignment on BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons");
static_assert(sizeof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons) == 0x001008, "Wrong size on BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, EntryPoint) == 0x000000, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_NormalizedDeltaRotator_ReturnValue) == 0x000008, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_NormalizedDeltaRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_NormalizedDeltaRotator_ReturnValue_1) == 0x000020, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_NormalizedDeltaRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_ReturnValue) == 0x000038, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeRotator_ReturnValue) == 0x000050, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_ReturnValue_1) == 0x000068, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeRotator_ReturnValue_1) == 0x000080, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_ReturnValue_2) == 0x000098, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeRotator_ReturnValue_2) == 0x0000B0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeRotator_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Lerp_ReturnValue) == 0x0000C8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Lerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_ReturnValue_3) == 0x0000D0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Lerp_ReturnValue_1) == 0x0000E8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Lerp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_ReturnValue_4) == 0x0000F0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Lerp_ReturnValue_2) == 0x000108, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Lerp_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_object_Variable) == 0x000110, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_ReturnValue_5) == 0x000120, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x000138, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_RLerp_ReturnValue) == 0x000150, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_RLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_IsClosed_Variable) == 0x000168, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_Has_Been_Initd_Variable) == 0x000169, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_IsClosed_Variable_1) == 0x00016A, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_Has_Been_Initd_Variable_1) == 0x00016B, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_IsClosed_Variable_2) == 0x00016C, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_IsClosed_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_Has_Been_Initd_Variable_2) == 0x00016D, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_Has_Been_Initd_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_IsClosed_Variable_3) == 0x00016E, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_IsClosed_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_IsClosed_Variable_4) == 0x00016F, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_IsClosed_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_Has_Been_Initd_Variable_3) == 0x000170, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_Has_Been_Initd_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_Has_Been_Initd_Variable_4) == 0x000171, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_Has_Been_Initd_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_Has_Been_Initd_Variable_5) == 0x000172, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_Has_Been_Initd_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_GetPlayerCameraManager_ReturnValue) == 0x000178, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_GetPlayerCameraManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_IsValid_ReturnValue) == 0x000180, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_GetPlayerCameraManager_ReturnValue_1) == 0x000188, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_GetPlayerCameraManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_AttachToActor_ReturnValue) == 0x000190, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_AttachToActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeRotation_SweepHitResult) == 0x000198, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x000280, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeRotation_SweepHitResult_1) == 0x000368, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeRotation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeLocation_SweepHitResult_1) == 0x000450, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeLocation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeRotation_SweepHitResult_2) == 0x000538, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeRotation_SweepHitResult_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeLocation_SweepHitResult_2) == 0x000620, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeLocation_SweepHitResult_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeLocation_SweepHitResult_3) == 0x000708, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeLocation_SweepHitResult_3' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeLocation_SweepHitResult_4) == 0x0007F0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeLocation_SweepHitResult_4' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeLocation_SweepHitResult_5) == 0x0008D8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeLocation_SweepHitResult_5' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_Event_DeltaSeconds) == 0x0009C0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x0009C8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_GetPlayerController_ReturnValue) == 0x0009D0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeRotator_ReturnValue_3) == 0x0009D8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeRotator_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_DeprojectMousePositionToWorld_WorldLocation) == 0x0009F0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_DeprojectMousePositionToWorld_WorldLocation' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_DeprojectMousePositionToWorld_WorldDirection) == 0x000A08, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_DeprojectMousePositionToWorld_WorldDirection' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_DeprojectMousePositionToWorld_ReturnValue) == 0x000A20, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_DeprojectMousePositionToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_GetPlayerCameraManager_ReturnValue_2) == 0x000A28, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_GetPlayerCameraManager_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Multiply_VectorVector_ReturnValue) == 0x000A30, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000A48, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Add_VectorVector_ReturnValue) == 0x000A60, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_LineTraceSingle_OutHit) == 0x000A78, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_LineTraceSingle_ReturnValue) == 0x000B60, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_CustomEvent_Highlight_2) == 0x000B61, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_CustomEvent_Highlight_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_bBlockingHit) == 0x000B62, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_bInitialOverlap) == 0x000B63, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_Time) == 0x000B64, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_Distance) == 0x000B68, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_Location) == 0x000B70, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_ImpactPoint) == 0x000B88, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_Normal) == 0x000BA0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_ImpactNormal) == 0x000BB8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_PhysMat) == 0x000BD0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_HitActor) == 0x000BD8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_HitComponent) == 0x000BE0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_HitBoneName) == 0x000BE8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_BoneName) == 0x000BF0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_HitItem) == 0x000BF8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_ElementIndex) == 0x000BFC, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_FaceIndex) == 0x000C00, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_TraceStart) == 0x000C08, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_BreakHitResult_TraceEnd) == 0x000C20, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Array_Get_Item) == 0x000C38, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_SwitchName_CmpSuccess) == 0x000C40, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_SwitchName_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000C41, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_CustomEvent_Highlight_1) == 0x000C42, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_CustomEvent_Highlight_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, Temp_bool_IsClosed_Variable_5) == 0x000C43, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::Temp_bool_IsClosed_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_CustomEvent_Highlight) == 0x000C44, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_CustomEvent_Highlight' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_GetAllWidgetsOfClass_FoundWidgets) == 0x000C48, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_GetAllWidgetsOfClass_FoundWidgets' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_GetPlayerController_ReturnValue_1) == 0x000C58, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_RemoveSaveWidget_WidgetsOut) == 0x000C60, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_RemoveSaveWidget_WidgetsOut' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Array_Get_Item_1) == 0x000C70, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Array_Length_ReturnValue) == 0x000C78, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_DynamicCast_AsMain_Menu_W) == 0x000C80, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_DynamicCast_AsMain_Menu_W' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_DynamicCast_bSuccess) == 0x000C88, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000C89, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Conv_IntToString_ReturnValue) == 0x000C90, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_DynamicCast_AsPC_Main_Menu) == 0x000CA0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_DynamicCast_AsPC_Main_Menu' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_DynamicCast_bSuccess_1) == 0x000CA8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_GetPlayerController_ReturnValue_2) == 0x000CB0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_GetPlayerController_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_GetPlayerController_ReturnValue_3) == 0x000CB8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_GetPlayerController_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_DynamicCast_AsPC_Main_Menu_1) == 0x000CC0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_DynamicCast_AsPC_Main_Menu_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_DynamicCast_bSuccess_2) == 0x000CC8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_DynamicCast_AsPC_Main_Menu_2) == 0x000CD0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_DynamicCast_AsPC_Main_Menu_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, K2Node_DynamicCast_bSuccess_3) == 0x000CD8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_AddRelativeRotation_SweepHitResult) == 0x000CE0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_AddRelativeRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000DC8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_VLerp_ReturnValue) == 0x000DE0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_VLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeLocation_SweepHitResult_6) == 0x000DF8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeLocation_SweepHitResult_6' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_K2_SetRelativeRotation_SweepHitResult_3) == 0x000EE0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_K2_SetRelativeRotation_SweepHitResult_3' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_Z_ImplicitCast) == 0x000FC8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_Z_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_Z_ImplicitCast_1) == 0x000FD0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_Z_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeVector_Z_ImplicitCast_2) == 0x000FD8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeVector_Z_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Lerp_Alpha_ImplicitCast) == 0x000FE0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Lerp_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Lerp_Alpha_ImplicitCast_1) == 0x000FE8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Lerp_Alpha_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Lerp_Alpha_ImplicitCast_2) == 0x000FF0, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Lerp_Alpha_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000FF8, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons, CallFunc_MakeRotator_Yaw_ImplicitCast) == 0x001000, "Member 'BP_MenuButtons_C_ExecuteUbergraph_BP_MenuButtons::CallFunc_MakeRotator_Yaw_ImplicitCast' has a wrong offset!");

// Function BP_MenuButtons.BP_MenuButtons_C.HighlightPlay
// 0x0001 (0x0001 - 0x0000)
struct BP_MenuButtons_C_HighlightPlay final
{
public:
	bool                                          Highlight;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MenuButtons_C_HighlightPlay) == 0x000001, "Wrong alignment on BP_MenuButtons_C_HighlightPlay");
static_assert(sizeof(BP_MenuButtons_C_HighlightPlay) == 0x000001, "Wrong size on BP_MenuButtons_C_HighlightPlay");
static_assert(offsetof(BP_MenuButtons_C_HighlightPlay, Highlight) == 0x000000, "Member 'BP_MenuButtons_C_HighlightPlay::Highlight' has a wrong offset!");

// Function BP_MenuButtons.BP_MenuButtons_C.HighlightQuit
// 0x0001 (0x0001 - 0x0000)
struct BP_MenuButtons_C_HighlightQuit final
{
public:
	bool                                          Highlight;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MenuButtons_C_HighlightQuit) == 0x000001, "Wrong alignment on BP_MenuButtons_C_HighlightQuit");
static_assert(sizeof(BP_MenuButtons_C_HighlightQuit) == 0x000001, "Wrong size on BP_MenuButtons_C_HighlightQuit");
static_assert(offsetof(BP_MenuButtons_C_HighlightQuit, Highlight) == 0x000000, "Member 'BP_MenuButtons_C_HighlightQuit::Highlight' has a wrong offset!");

// Function BP_MenuButtons.BP_MenuButtons_C.HighlightSettings
// 0x0001 (0x0001 - 0x0000)
struct BP_MenuButtons_C_HighlightSettings final
{
public:
	bool                                          Highlight;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MenuButtons_C_HighlightSettings) == 0x000001, "Wrong alignment on BP_MenuButtons_C_HighlightSettings");
static_assert(sizeof(BP_MenuButtons_C_HighlightSettings) == 0x000001, "Wrong size on BP_MenuButtons_C_HighlightSettings");
static_assert(offsetof(BP_MenuButtons_C_HighlightSettings, Highlight) == 0x000000, "Member 'BP_MenuButtons_C_HighlightSettings::Highlight' has a wrong offset!");

// Function BP_MenuButtons.BP_MenuButtons_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_MenuButtons_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MenuButtons_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_MenuButtons_C_ReceiveTick");
static_assert(sizeof(BP_MenuButtons_C_ReceiveTick) == 0x000004, "Wrong size on BP_MenuButtons_C_ReceiveTick");
static_assert(offsetof(BP_MenuButtons_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_MenuButtons_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_MenuButtons.BP_MenuButtons_C.RemoveSaveWidget
// 0x0098 (0x0098 - 0x0000)
struct BP_MenuButtons_C_RemoveSaveWidget final
{
public:
	TArray<class UUserWidget*>                    Widgets;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UUserWidget*>                    WidgetsOut;                                        // 0x0010(0x0010)(Parm, OutParm, ContainsInstancedReference)
	TArray<class UUserWidget*>                    NewLocalVar;                                       // 0x0020(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UDownloadHUD_w_C*>               CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0048(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UDownloadHUD_w_C*                       CallFunc_Array_Get_Item;                           // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0065(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_66[0x2];                                       // 0x0066(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UW_SaveNotif_C*>                 CallFunc_GetAllWidgetsOfClass_FoundWidgets_1;      // 0x0070(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_SaveNotif_C*                         CallFunc_Array_Get_Item_1;                         // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue_1;           // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MenuButtons_C_RemoveSaveWidget) == 0x000008, "Wrong alignment on BP_MenuButtons_C_RemoveSaveWidget");
static_assert(sizeof(BP_MenuButtons_C_RemoveSaveWidget) == 0x000098, "Wrong size on BP_MenuButtons_C_RemoveSaveWidget");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, Widgets) == 0x000000, "Member 'BP_MenuButtons_C_RemoveSaveWidget::Widgets' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, WidgetsOut) == 0x000010, "Member 'BP_MenuButtons_C_RemoveSaveWidget::WidgetsOut' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, NewLocalVar) == 0x000020, "Member 'BP_MenuButtons_C_RemoveSaveWidget::NewLocalVar' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, Temp_int_Loop_Counter_Variable) == 0x000030, "Member 'BP_MenuButtons_C_RemoveSaveWidget::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Add_IntInt_ReturnValue) == 0x000034, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, Temp_int_Array_Index_Variable) == 0x000038, "Member 'BP_MenuButtons_C_RemoveSaveWidget::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, Temp_int_Array_Index_Variable_1) == 0x00003C, "Member 'BP_MenuButtons_C_RemoveSaveWidget::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, Temp_int_Loop_Counter_Variable_1) == 0x000040, "Member 'BP_MenuButtons_C_RemoveSaveWidget::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_GetAllWidgetsOfClass_FoundWidgets) == 0x000048, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_GetAllWidgetsOfClass_FoundWidgets' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Array_Get_Item) == 0x000058, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Array_Length_ReturnValue) == 0x000060, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Array_RemoveItem_ReturnValue) == 0x000064, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Less_IntInt_ReturnValue) == 0x000065, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Add_IntInt_ReturnValue_1) == 0x000068, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_GetAllWidgetsOfClass_FoundWidgets_1) == 0x000070, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_GetAllWidgetsOfClass_FoundWidgets_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Array_Length_ReturnValue_1) == 0x000080, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Array_Get_Item_1) == 0x000088, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Less_IntInt_ReturnValue_1) == 0x000090, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_RemoveSaveWidget, CallFunc_Array_RemoveItem_ReturnValue_1) == 0x000091, "Member 'BP_MenuButtons_C_RemoveSaveWidget::CallFunc_Array_RemoveItem_ReturnValue_1' has a wrong offset!");

// Function BP_MenuButtons.BP_MenuButtons_C.ResetHover
// 0x0020 (0x0020 - 0x0000)
struct BP_MenuButtons_C_ResetHover final
{
public:
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APC_MainMenu_C*                         K2Node_DynamicCast_AsPC_Main_Menu;                 // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MenuButtons_C_ResetHover) == 0x000008, "Wrong alignment on BP_MenuButtons_C_ResetHover");
static_assert(sizeof(BP_MenuButtons_C_ResetHover) == 0x000020, "Wrong size on BP_MenuButtons_C_ResetHover");
static_assert(offsetof(BP_MenuButtons_C_ResetHover, CallFunc_GetPlayerController_ReturnValue) == 0x000000, "Member 'BP_MenuButtons_C_ResetHover::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ResetHover, CallFunc_GetPlayerController_ReturnValue_1) == 0x000008, "Member 'BP_MenuButtons_C_ResetHover::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ResetHover, K2Node_DynamicCast_AsPC_Main_Menu) == 0x000010, "Member 'BP_MenuButtons_C_ResetHover::K2Node_DynamicCast_AsPC_Main_Menu' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_ResetHover, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_MenuButtons_C_ResetHover::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_MenuButtons.BP_MenuButtons_C.UserConstructionScript
// 0x0020 (0x0020 - 0x0000)
struct BP_MenuButtons_C_UserConstructionScript final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_1; // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_2; // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_3; // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MenuButtons_C_UserConstructionScript) == 0x000008, "Wrong alignment on BP_MenuButtons_C_UserConstructionScript");
static_assert(sizeof(BP_MenuButtons_C_UserConstructionScript) == 0x000020, "Wrong size on BP_MenuButtons_C_UserConstructionScript");
static_assert(offsetof(BP_MenuButtons_C_UserConstructionScript, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000000, "Member 'BP_MenuButtons_C_UserConstructionScript::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_UserConstructionScript, CallFunc_CreateDynamicMaterialInstance_ReturnValue_1) == 0x000008, "Member 'BP_MenuButtons_C_UserConstructionScript::CallFunc_CreateDynamicMaterialInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_UserConstructionScript, CallFunc_CreateDynamicMaterialInstance_ReturnValue_2) == 0x000010, "Member 'BP_MenuButtons_C_UserConstructionScript::CallFunc_CreateDynamicMaterialInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MenuButtons_C_UserConstructionScript, CallFunc_CreateDynamicMaterialInstance_ReturnValue_3) == 0x000018, "Member 'BP_MenuButtons_C_UserConstructionScript::CallFunc_CreateDynamicMaterialInstance_ReturnValue_3' has a wrong offset!");

}

