#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TurningPlate

#include "Basic.hpp"

#include "BP_TurningPlate_classes.hpp"
#include "BP_TurningPlate_parameters.hpp"


namespace SDK
{

// Function BP_TurningPlate.BP_TurningPlate_C.ExecuteUbergraph_BP_TurningPlate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TurningPlate_C::ExecuteUbergraph_BP_TurningPlate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurningPlate_C", "ExecuteUbergraph_BP_TurningPlate");

	Params::BP_TurningPlate_C_ExecuteUbergraph_BP_TurningPlate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TurningPlate.BP_TurningPlate_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TurningPlate_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TurningPlate_C", "ReceiveTick");

	Params::BP_TurningPlate_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

