#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CreatingGameMenu

#include "Basic.hpp"

#include "S_BiomeSave_structs.hpp"


namespace SDK::Params
{

// Function BPI_CreatingGameMenu.BPI_CreatingGameMenu_C.RefreshSave
// 0x0038 (0x0038 - 0x0000)
struct BPI_CreatingGameMenu_C_RefreshSave final
{
public:
	struct FS_BiomeSave                           Save;                                              // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_CreatingGameMenu_C_RefreshSave) == 0x000008, "Wrong alignment on BPI_CreatingGameMenu_C_RefreshSave");
static_assert(sizeof(BPI_CreatingGameMenu_C_RefreshSave) == 0x000038, "Wrong size on BPI_CreatingGameMenu_C_RefreshSave");
static_assert(offsetof(BPI_CreatingGameMenu_C_RefreshSave, Save) == 0x000000, "Member 'BPI_CreatingGameMenu_C_RefreshSave::Save' has a wrong offset!");

}

