#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IGLE_TextureWidget

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "IGLE_W_PropertyValueWidgetBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass IGLE_TextureWidget.IGLE_TextureWidget_C
// 0x0010 (0x02D8 - 0x02C8)
class UIGLE_TextureWidget_C final : public UIGLE_W_PropertyValueWidgetBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UComboBoxString*                        ComboBoxString_75;                                 // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__IGLE_TextureWidget_ComboBoxString_75_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void Construct();
	void ExecuteUbergraph_IGLE_TextureWidget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IGLE_TextureWidget_C">();
	}
	static class UIGLE_TextureWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIGLE_TextureWidget_C>();
	}
};
static_assert(alignof(UIGLE_TextureWidget_C) == 0x000008, "Wrong alignment on UIGLE_TextureWidget_C");
static_assert(sizeof(UIGLE_TextureWidget_C) == 0x0002D8, "Wrong size on UIGLE_TextureWidget_C");
static_assert(offsetof(UIGLE_TextureWidget_C, UberGraphFrame) == 0x0002C8, "Member 'UIGLE_TextureWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UIGLE_TextureWidget_C, ComboBoxString_75) == 0x0002D0, "Member 'UIGLE_TextureWidget_C::ComboBoxString_75' has a wrong offset!");

}

