#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IGLE_Action_ChangeSelection

#include "Basic.hpp"

#include "InGameLevelEditor_structs.hpp"


namespace SDK::Params
{

// Function IGLE_Action_ChangeSelection.IGLE_Action_ChangeSelection_C.ExecuteUbergraph_IGLE_Action_ChangeSelection
// 0x0098 (0x0098 - 0x0000)
struct IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CallFunc_Set_ToArray_Result;                       // 0x0018(0x0010)(ReferenceParm)
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FIGLEActorReference                    CallFunc_IGLE_MakeActorReference_Reference;        // 0x0038(0x0018)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IGLE_MakeActorReference_ReturnValue;      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52[0x2];                                       // 0x0052(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CallFunc_Set_ToArray_Result_1;                     // 0x0058(0x0010)(ReferenceParm)
	class AActor*                                 CallFunc_Array_Get_Item_1;                         // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FIGLEActorReference                    CallFunc_IGLE_MakeActorReference_Reference_1;      // 0x0078(0x0018)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IGLE_MakeActorReference_ReturnValue_1;    // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection) == 0x000008, "Wrong alignment on IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection");
static_assert(sizeof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection) == 0x000098, "Wrong size on IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, EntryPoint) == 0x000000, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::EntryPoint' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, Temp_int_Array_Index_Variable_1) == 0x000010, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, Temp_int_Loop_Counter_Variable_1) == 0x000014, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Set_ToArray_Result) == 0x000018, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Set_ToArray_Result' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Array_Get_Item) == 0x000028, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Array_Length_ReturnValue) == 0x000030, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_IGLE_MakeActorReference_Reference) == 0x000038, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_IGLE_MakeActorReference_Reference' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_IGLE_MakeActorReference_ReturnValue) == 0x000050, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_IGLE_MakeActorReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Less_IntInt_ReturnValue) == 0x000051, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Add_IntInt_ReturnValue_1) == 0x000054, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Set_ToArray_Result_1) == 0x000058, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Set_ToArray_Result_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Array_Get_Item_1) == 0x000068, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Array_Length_ReturnValue_1) == 0x000070, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_IGLE_MakeActorReference_Reference_1) == 0x000078, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_IGLE_MakeActorReference_Reference_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_IGLE_MakeActorReference_ReturnValue_1) == 0x000090, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_IGLE_MakeActorReference_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection, CallFunc_Less_IntInt_ReturnValue_1) == 0x000091, "Member 'IGLE_Action_ChangeSelection_C_ExecuteUbergraph_IGLE_Action_ChangeSelection::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");

// Function IGLE_Action_ChangeSelection.IGLE_Action_ChangeSelection_C.GetFriendlyActionName
// 0x0010 (0x0010 - 0x0000)
struct IGLE_Action_ChangeSelection_C_GetFriendlyActionName final
{
public:
	class FString                                 OutName;                                           // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(IGLE_Action_ChangeSelection_C_GetFriendlyActionName) == 0x000008, "Wrong alignment on IGLE_Action_ChangeSelection_C_GetFriendlyActionName");
static_assert(sizeof(IGLE_Action_ChangeSelection_C_GetFriendlyActionName) == 0x000010, "Wrong size on IGLE_Action_ChangeSelection_C_GetFriendlyActionName");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_GetFriendlyActionName, OutName) == 0x000000, "Member 'IGLE_Action_ChangeSelection_C_GetFriendlyActionName::OutName' has a wrong offset!");

// Function IGLE_Action_ChangeSelection.IGLE_Action_ChangeSelection_C.RedoSelection
// 0x0108 (0x0108 - 0x0000)
struct IGLE_Action_ChangeSelection_C_RedoSelection final
{
public:
	TSet<class AActor*>                           NewSelectionTemp;                                  // 0x0000(0x0050)(Edit, BlueprintVisible, DisableEditOnTemplate)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_Set_ToArray_Result;                       // 0x0068(0x0010)(ReferenceParm)
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CallFunc_Set_ToArray_Result_1;                     // 0x0080(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item_1;                         // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Set_Contains_ReturnValue;                 // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A5[0x3];                                       // 0x00A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Set_Contains_ReturnValue_1;               // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BA[0x2];                                       // 0x00BA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FIGLEActorReference>            CallFunc_Set_ToArray_Result_2;                     // 0x00C0(0x0010)(ReferenceParm)
	struct FIGLEActorReference                    CallFunc_Array_Get_Item_2;                         // 0x00D0(0x0018)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_IGLE_GetActorReference_ReturnValue;       // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F9[0x3];                                       // 0x00F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(IGLE_Action_ChangeSelection_C_RedoSelection) == 0x000008, "Wrong alignment on IGLE_Action_ChangeSelection_C_RedoSelection");
static_assert(sizeof(IGLE_Action_ChangeSelection_C_RedoSelection) == 0x000108, "Wrong size on IGLE_Action_ChangeSelection_C_RedoSelection");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, NewSelectionTemp) == 0x000000, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::NewSelectionTemp' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, Temp_int_Array_Index_Variable) == 0x000050, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, Temp_int_Array_Index_Variable_1) == 0x000054, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, Temp_int_Loop_Counter_Variable) == 0x000058, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Add_IntInt_ReturnValue) == 0x00005C, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, Temp_int_Array_Index_Variable_2) == 0x000060, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Set_ToArray_Result) == 0x000068, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Set_ToArray_Result' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Array_Get_Item) == 0x000078, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Set_ToArray_Result_1) == 0x000080, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Set_ToArray_Result_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Array_Length_ReturnValue) == 0x000090, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Array_Get_Item_1) == 0x000098, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Array_Length_ReturnValue_1) == 0x0000A0, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Set_Contains_ReturnValue) == 0x0000A4, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Set_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, Temp_int_Loop_Counter_Variable_1) == 0x0000A8, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Less_IntInt_ReturnValue) == 0x0000AC, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Add_IntInt_ReturnValue_1) == 0x0000B0, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, Temp_int_Loop_Counter_Variable_2) == 0x0000B4, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Set_Contains_ReturnValue_1) == 0x0000B8, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Set_Contains_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000B9, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Add_IntInt_ReturnValue_2) == 0x0000BC, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Set_ToArray_Result_2) == 0x0000C0, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Set_ToArray_Result_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Array_Get_Item_2) == 0x0000D0, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_IsValid_ReturnValue) == 0x0000E8, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_IGLE_GetActorReference_ReturnValue) == 0x0000F0, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_IGLE_GetActorReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_IsValid_ReturnValue_1) == 0x0000F8, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Array_Length_ReturnValue_2) == 0x0000FC, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_RedoSelection, CallFunc_Less_IntInt_ReturnValue_2) == 0x000100, "Member 'IGLE_Action_ChangeSelection_C_RedoSelection::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");

// Function IGLE_Action_ChangeSelection.IGLE_Action_ChangeSelection_C.UndoSelection
// 0x0100 (0x0100 - 0x0000)
struct IGLE_Action_ChangeSelection_C_UndoSelection final
{
public:
	TSet<class AActor*>                           OldSelectionTemp;                                  // 0x0000(0x0050)(Edit, BlueprintVisible, DisableEditOnTemplate)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CallFunc_Set_ToArray_Result;                       // 0x0068(0x0010)(ReferenceParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Set_Contains_ReturnValue;                 // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CallFunc_Set_ToArray_Result_1;                     // 0x0090(0x0010)(ReferenceParm)
	class AActor*                                 CallFunc_Array_Get_Item_1;                         // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Set_Contains_ReturnValue_1;               // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00AD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AE[0x2];                                       // 0x00AE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B5[0x3];                                       // 0x00B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FIGLEActorReference>            CallFunc_Set_ToArray_Result_2;                     // 0x00C0(0x0010)(ReferenceParm)
	struct FIGLEActorReference                    CallFunc_Array_Get_Item_2;                         // 0x00D0(0x0018)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_IGLE_GetActorReference_ReturnValue;       // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(IGLE_Action_ChangeSelection_C_UndoSelection) == 0x000008, "Wrong alignment on IGLE_Action_ChangeSelection_C_UndoSelection");
static_assert(sizeof(IGLE_Action_ChangeSelection_C_UndoSelection) == 0x000100, "Wrong size on IGLE_Action_ChangeSelection_C_UndoSelection");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, OldSelectionTemp) == 0x000000, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::OldSelectionTemp' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, Temp_int_Array_Index_Variable) == 0x000050, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, Temp_int_Array_Index_Variable_1) == 0x000054, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, Temp_int_Loop_Counter_Variable) == 0x000058, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Add_IntInt_ReturnValue) == 0x00005C, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, Temp_int_Array_Index_Variable_2) == 0x000060, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, Temp_int_Loop_Counter_Variable_1) == 0x000064, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Set_ToArray_Result) == 0x000068, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Set_ToArray_Result' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Add_IntInt_ReturnValue_1) == 0x000078, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Array_Get_Item) == 0x000080, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Set_Contains_ReturnValue) == 0x000088, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Set_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Array_Length_ReturnValue) == 0x00008C, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Set_ToArray_Result_1) == 0x000090, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Set_ToArray_Result_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Array_Get_Item_1) == 0x0000A0, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Array_Length_ReturnValue_1) == 0x0000A8, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Set_Contains_ReturnValue_1) == 0x0000AC, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Set_Contains_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Less_IntInt_ReturnValue) == 0x0000AD, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, Temp_int_Loop_Counter_Variable_2) == 0x0000B0, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000B4, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Add_IntInt_ReturnValue_2) == 0x0000B8, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_IsValid_ReturnValue) == 0x0000BC, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Set_ToArray_Result_2) == 0x0000C0, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Set_ToArray_Result_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Array_Get_Item_2) == 0x0000D0, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Array_Length_ReturnValue_2) == 0x0000E8, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_IGLE_GetActorReference_ReturnValue) == 0x0000F0, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_IGLE_GetActorReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000F8, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(IGLE_Action_ChangeSelection_C_UndoSelection, CallFunc_IsValid_ReturnValue_1) == 0x0000F9, "Member 'IGLE_Action_ChangeSelection_C_UndoSelection::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

}

