#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IGLE_W_SplinePointPropertyValueWidget

#include "Basic.hpp"

#include "IGLE_W_SplinePointPropertyValueWidget_classes.hpp"
#include "IGLE_W_SplinePointPropertyValueWidget_parameters.hpp"


namespace SDK
{

// Function IGLE_W_SplinePointPropertyValueWidget.IGLE_W_SplinePointPropertyValueWidget_C.BndEvt__IGLE_W_SplinePointPropertyValueWidget_Minus_Button_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UIGLE_W_SplinePointPropertyValueWidget_C::BndEvt__IGLE_W_SplinePointPropertyValueWidget_Minus_Button_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IGLE_W_SplinePointPropertyValueWidget_C", "BndEvt__IGLE_W_SplinePointPropertyValueWidget_Minus_Button_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IGLE_W_SplinePointPropertyValueWidget.IGLE_W_SplinePointPropertyValueWidget_C.BndEvt__IGLE_W_SplinePointPropertyValueWidget_Plus_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UIGLE_W_SplinePointPropertyValueWidget_C::BndEvt__IGLE_W_SplinePointPropertyValueWidget_Plus_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IGLE_W_SplinePointPropertyValueWidget_C", "BndEvt__IGLE_W_SplinePointPropertyValueWidget_Plus_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IGLE_W_SplinePointPropertyValueWidget.IGLE_W_SplinePointPropertyValueWidget_C.ExecuteUbergraph_IGLE_W_SplinePointPropertyValueWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIGLE_W_SplinePointPropertyValueWidget_C::ExecuteUbergraph_IGLE_W_SplinePointPropertyValueWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IGLE_W_SplinePointPropertyValueWidget_C", "ExecuteUbergraph_IGLE_W_SplinePointPropertyValueWidget");

	Params::IGLE_W_SplinePointPropertyValueWidget_C_ExecuteUbergraph_IGLE_W_SplinePointPropertyValueWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IGLE_W_SplinePointPropertyValueWidget.IGLE_W_SplinePointPropertyValueWidget_C.GetText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UIGLE_W_SplinePointPropertyValueWidget_C::GetText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IGLE_W_SplinePointPropertyValueWidget_C", "GetText");

	Params::IGLE_W_SplinePointPropertyValueWidget_C_GetText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

