#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadSaveSwitcher_W

#include "Basic.hpp"

#include "LoadSaveSwitcher_W_classes.hpp"
#include "LoadSaveSwitcher_W_parameters.hpp"


namespace SDK
{

// Function LoadSaveSwitcher_W.LoadSaveSwitcher_W_C.BndEvt__LoadSaveSwitcher_W_BackButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULoadSaveSwitcher_W_C::BndEvt__LoadSaveSwitcher_W_BackButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadSaveSwitcher_W_C", "BndEvt__LoadSaveSwitcher_W_BackButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadSaveSwitcher_W.LoadSaveSwitcher_W_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULoadSaveSwitcher_W_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadSaveSwitcher_W_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadSaveSwitcher_W.LoadSaveSwitcher_W_C.ExecuteUbergraph_LoadSaveSwitcher_W
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadSaveSwitcher_W_C::ExecuteUbergraph_LoadSaveSwitcher_W(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadSaveSwitcher_W_C", "ExecuteUbergraph_LoadSaveSwitcher_W");

	Params::LoadSaveSwitcher_W_C_ExecuteUbergraph_LoadSaveSwitcher_W Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

