#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Magnolia_01_BP

#include "Basic.hpp"

#include "Magnolia_01_BP_classes.hpp"
#include "Magnolia_01_BP_parameters.hpp"


namespace SDK
{

// Function magnolia_01_BP.magnolia_01_BP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AMagnolia_01_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("magnolia_01_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

