#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mod_RescuePoint

#include "Basic.hpp"

#include "BP_RescuePoint_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mod_RescuePoint.Mod_RescuePoint_C
// 0x0000 (0x0310 - 0x0310)
class AMod_RescuePoint_C final : public ABP_RescuePoint_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Mod_RescuePoint_C">();
	}
	static class AMod_RescuePoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMod_RescuePoint_C>();
	}
};
static_assert(alignof(AMod_RescuePoint_C) == 0x000008, "Wrong alignment on AMod_RescuePoint_C");
static_assert(sizeof(AMod_RescuePoint_C) == 0x000310, "Wrong size on AMod_RescuePoint_C");

}

