#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Troubleshooting_W

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Troubleshooting_W.Troubleshooting_W_C
// 0x0010 (0x02D0 - 0x02C0)
class UTroubleshooting_W_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_445;                                        // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__Troubleshooting_W_Button_445_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void ExecuteUbergraph_Troubleshooting_W(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Troubleshooting_W_C">();
	}
	static class UTroubleshooting_W_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTroubleshooting_W_C>();
	}
};
static_assert(alignof(UTroubleshooting_W_C) == 0x000008, "Wrong alignment on UTroubleshooting_W_C");
static_assert(sizeof(UTroubleshooting_W_C) == 0x0002D0, "Wrong size on UTroubleshooting_W_C");
static_assert(offsetof(UTroubleshooting_W_C, UberGraphFrame) == 0x0002C0, "Member 'UTroubleshooting_W_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UTroubleshooting_W_C, Button_445) == 0x0002C8, "Member 'UTroubleshooting_W_C::Button_445' has a wrong offset!");

}

