#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SessionButton

#include "Basic.hpp"

#include "W_SessionButton_classes.hpp"
#include "W_SessionButton_parameters.hpp"


namespace SDK
{

// Function W_SessionButton.W_SessionButton_C.BndEvt__W_SessionButton_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_SessionButton_C::BndEvt__W_SessionButton_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "BndEvt__W_SessionButton_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_SessionButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.ExecuteUbergraph_W_SessionButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SessionButton_C::ExecuteUbergraph_W_SessionButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "ExecuteUbergraph_W_SessionButton");

	Params::W_SessionButton_C_ExecuteUbergraph_W_SessionButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SessionButton.W_SessionButton_C.OnFailure_FF5E99A8492661E2A8712A9CB50488D3
// (BlueprintCallable, BlueprintEvent)

void UW_SessionButton_C::OnFailure_FF5E99A8492661E2A8712A9CB50488D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "OnFailure_FF5E99A8492661E2A8712A9CB50488D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.OnSuccess_FF5E99A8492661E2A8712A9CB50488D3
// (BlueprintCallable, BlueprintEvent)

void UW_SessionButton_C::OnSuccess_FF5E99A8492661E2A8712A9CB50488D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "OnSuccess_FF5E99A8492661E2A8712A9CB50488D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.ResetJoinSession
// (BlueprintCallable, BlueprintEvent)

void UW_SessionButton_C::ResetJoinSession()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "ResetJoinSession");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.UpdateMode
// (Public, BlueprintCallable, BlueprintEvent)

void UW_SessionButton_C::UpdateMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "UpdateMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.UpdateName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_SessionButton_C::UpdateName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "UpdateName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.UpdatePassword
// (Public, BlueprintCallable, BlueprintEvent)

void UW_SessionButton_C::UpdatePassword()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "UpdatePassword");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.UpdatePing
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_SessionButton_C::UpdatePing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "UpdatePing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SessionButton.W_SessionButton_C.UpdatePlayers
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_SessionButton_C::UpdatePlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SessionButton_C", "UpdatePlayers");

	UObject::ProcessEvent(Func, nullptr);
}

}

