#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SpeedRun_PlayerName

#include "Basic.hpp"

#include "W_SpeedRun_PlayerName_classes.hpp"
#include "W_SpeedRun_PlayerName_parameters.hpp"


namespace SDK
{

// Function W_SpeedRun_PlayerName.W_SpeedRun_PlayerName_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_SpeedRun_PlayerName_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SpeedRun_PlayerName_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SpeedRun_PlayerName.W_SpeedRun_PlayerName_C.ExecuteUbergraph_W_SpeedRun_PlayerName
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SpeedRun_PlayerName_C::ExecuteUbergraph_W_SpeedRun_PlayerName(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SpeedRun_PlayerName_C", "ExecuteUbergraph_W_SpeedRun_PlayerName");

	Params::W_SpeedRun_PlayerName_C_ExecuteUbergraph_W_SpeedRun_PlayerName Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

